//
//  CoreDataUtilityStyle.h
//  CoreDataUtilityStyle
//
//  Created by Chris Wilson on 5/29/14.
//  Copyright (c) 2014 mFluent LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface CoreDataUtilityStyle : NSObject

// Colors
+ (NSColor*)brown;
+ (NSColor*)theTextColor;
+ (NSColor*)blue;
+ (NSColor*)gray;
+ (NSColor*)objectBackground;
+ (NSColor*)entitySetBorder;

// Drawing Methods
+ (void)drawFetch;
+ (void)drawEntity;
+ (void)drawEntitySet;
+ (void)drawNumber;
+ (void)drawBinary;
+ (void)drawBoolean;
+ (void)drawDate;
+ (void)drawAnObject;
+ (void)drawAString;

// Generated Images
+ (NSImage*)imageOfFetch;
+ (NSImage*)imageOfEntity;
+ (NSImage*)imageOfEntitySet;
+ (NSImage*)imageOfNumber;
+ (NSImage*)imageOfBinary;
+ (NSImage*)imageOfBoolean;
+ (NSImage*)imageOfDate;
+ (NSImage*)imageOfAnObject;
+ (NSImage*)imageOfAString;

@end
